on:
  #schedule:
    #- cron:  '0 18 * * 4'
  workflow_dispatch:

name: check-ver
jobs:
  check-ver:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Check XyVer
        run: |  
          xy_latest=$(curl -s "https://api.github.com/repos/XTLS/Xray-core/releases/latest" | sed 'y/,/\n/' | grep 'tag_name' | awk -F '"' '{print substr($4,2)}')
          xy_current=$(./releases/xy version | awk 'NR==1 {print $2}')
          echo xy latest:${xy_latest}
          echo xy current:${xy_current}
        
      - name: Check CaddyVer
        run: |  
          cadyy_latest=$(curl -s "https://api.github.com/repos/caddyserver/caddy/releases/latest" | sed 'y/,/\n/' | grep 'tag_name' | awk -F '"' '{print substr($4,2)}')
          caddy_current=$(./releases/caddy version | awk 'NR==1 {print $2}')
          echo cddy latest:${caddy_latest}
          echo cddy current:${caddy_current}
          
