on:
  #schedule:
    #- cron:  '0 18 * * 4'
  workflow_dispatch:

name: latest
jobs:
  latest:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: xy
        run: | 
          cd ./releases/
          RELEASE_LATEST=$(curl -s "https://api.github.com/repos/XTLS/Xray-core/releases/latest" | sed 'y/,/\n/' | grep 'tag_name' | awk -F '"' '{print substr($4,2)}')
          RELEASE_VERSION="v${RELEASE_LATEST#v}"
          wget -O xy.zip https://github.com/XTLS/Xray-core/releases/download/$RELEASE_VERSION/Xray-linux-64.zip 
          unzip xy.zip
          rm -rf ./xy.zip ./LICENSE ./*.md ./*.dat 
          mv ./xray ./xy

      - name: caddy
        run: | 
          RELEASE_LATEST=$(curl -s "https://api.github.com/repos/caddyserver/caddy/releases/latest" | grep "tag_name" | cut -d\" -f4 | sed -e "s/^v//" -e "s/-.$//" | cut -d"v" -f 2)
          RELEASE_VERSION="v${RELEASE_LATEST#v}"
          wget -O caddy.tar.gz "https://github.com/caddyserver/caddy/releases/download/$RELEASE_VERSION/caddy_${RELEASE_LATEST}_linux_amd64.tar.gz"
          tar x -z -f caddy.tar.gz -C ./releases caddy
          rm -f ./caddy.tar.gz ./LICENSE ./*.md

      - name: commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add .
          git commit --allow-empty -m "$(git log -1 --pretty=%s)"
          git push
