on:
  #schedule:
    #- cron:  '0 18 * * 4'
  workflow_dispatch:

name: test-xy-11
jobs:
  test-xy-11:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: xy
        run: | 
          cd ./releases/
          wget -O Caddyfile https://raw.githubusercontent.com/chadsodi/xddy/main/releases/Caddyfile
          wget -O entrypoint.sh https://raw.githubusercontent.com/chadsodi/xddy/main/releases/entrypoint.sh
          wget -O html.tar.gz https://raw.githubusercontent.com/chadsodi/xddy/main/releases/html.tar.gz
          cd ../
          wget -O Dockerfile https://raw.githubusercontent.com/chadsodi/xddy/main/Dockerfile
          wget -O README.md https://raw.githubusercontent.com/chadsodi/xddy/main/README.md
      - name: commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add .
          git commit --allow-empty -m "$(git log -1 --pretty=%s)"
          git push
